routes/dashboard.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Dashboard\CameraController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;


Route::group(['prefix' => 'admin'], function (){
    Route::get('/', [CameraController::class,'login']);
    Route::post('login', [LoginController::class,'login'])->name('admin.login');
});

Route::group(['prefix' => 'dashboard','middleware' => ['auth','admin','preventBack']], function (){
    Route::get('/main', function () {
        return view('dashboard.layout.index');
    })->name('dashboard');
   Route::resource('/cameras','\App\Http\Controllers\Dashboard\CameraController');
   Route::post('/ajax/rahbarId',[CameraController::class, 'ajaxGetRahbarId'])->name('ajax.getRahbarId');
   Route::post('/ajax/getId',[CameraController::class, 'ajaxGetSubId'])->name('ajax.getSubId');
   Route::post('/ajax/getBinolar',[CameraController::class, 'ajaxXonalar'])->name('ajax.xonalar');
   Route::post('/cameras/filter',[CameraController::class, 'indexFilter'])->name('camera.filter');
//   rektor

//   rektor
});
Route::middleware(['middleware'=>'preventBack'])->group(function (){
    Auth::routes();
});

routes/web.php
<?php

use App\Http\Controllers\Web\CameraController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes

|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

Route::get('/kirish',[CameraController::class,'loginPage'])->name('user.loginPage');
Route::post('/user/login',[CameraController::class,'login'])->name('user.login');

Route::get('/',[CameraController::class,'userShowAllCamera'])->name('user.camera');
Route::get('/camera/{sub_id}',[CameraController::class,'userSubShowAllCamera'])->name('user.cameraSub');

Route::group(['prefix' => 'web', 'middleware' => ['user','preventBack']], function (){
    Route::get('/index',[\App\Http\Controllers\Web\CameraController::class, 'index'])->name('web');
    Route::post('/ajax', [\App\Http\Controllers\Web\CameraController::class, 'ajax'])->name('camera.ajax');

////rektor
//    Route::post('/ajax/getId/rektor',[CameraController::class, 'ajaxGetSubId'])->name('ajax.getSubIdRektor');
//    Route::get('/rektor/section', [CameraController::class,'getSection'])->name('camera.rektorSection');
//    Route::post('/rektor', [CameraController::class,'rektor'])->name('camera.rektor');
////rektor
});


//Route::get('/', [\App\Http\Controllers\Web\CameraController::class, 'index'])->name('web.index');

app/Http/Controllers/Dashboard/CameraApiController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Domain\Cameras\Models\Camera;
use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CameraApiController extends Controller
{
    /**
     * @var mixed
     */
    private $api_url;

    /**
     * @var mixed
     */
    private $api_port;

    /**
     *
     */
    public function __construct()
    {
        $this->api_url = env('API_URL');
        $this->api_port = env('API_PORT');
    }

    /**
     * @return JsonResponse
     */
    public function getAllCamera()
    {
        $cameras = Camera::select('id','xona_id','name','uuid')->get();

        $array_cameras = array();

        for ($i=0; $i<count($cameras); $i++){
            $array_cameras[$i] = [
                'id' => $cameras[$i]->id,
                'xona_id' => $cameras[$i]->xona_id,
                'nomi' => $cameras[$i]->name,
                'link' => 'http://' . $this->api_url . ':' . $this->api_port . '/stream/' . $cameras[$i]->uuid . '/channel/0/hls/live/index.m3u8'
            ];
        }

        return response()->json([
            'cameras' => $array_cameras
        ],200)->setEncodingOptions(JSON_UNESCAPED_SLASHES);
    }

    /**
     * @param Request $request
     * @return JsonResponse
     */
    public function camera(Request $request)
    {

        $cameras = Camera::select('id','xona_id','name','uuid')
            ->where('xona_id','=', $request->xona_id)
            ->get();

        $array_camera = array();

        for ($i=0; $i<count($cameras); $i++){
            $array_camera[$i] = [
                'id' => $cameras[$i]->id,
                'xona_id' => $cameras[$i]->xona_id,
                'nomi' => $cameras[$i]->name,
                'link' => 'http://' . $this->api_url . ':' . $this->api_port . '/stream/' . $cameras[$i]->uuid . '/channel/0/hls/live/index.m3u8'
            ];
        }

        return response()->json([
            'data'=> $array_camera,
        ])->setEncodingOptions(JSON_UNESCAPED_SLASHES);
    }
}

app/Http/Controllers/Dashboard/CameraController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Domain\Cameras\Models\Camera;
use App\Domain\Cameras\Repositories\CameraRepository;
use App\Http\Controllers\Controller;
use GuzzleHttp\Exception\GuzzleException;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Str;

class CameraController extends Controller
{
    /**
     * @var mixed
     */
    private $api_url;

    /**
     * @var mixed
     */
    private $api_port;

    /**
     * @var mixed
     */
    private $api_login;

    /**
     * @var mixed
     */
    private $api_password;

    /**
     *
     */
    public function __construct()
    {
        $this->api_url = env('API_URL');
        $this->api_port = env('API_PORT');
        $this->api_login = env('API_LOGIN');
        $this->api_password = env('API_PASSWORD');
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @param CameraRepository $cameraRepository
     * @return Factory|View
     * @throws GuzzleException
     */
    public function index(Request $request, CameraRepository $cameraRepository)
    {
        $client = new \GuzzleHttp\Client();
        $response = $client->request('GET', 'https://uniwork.buxdu.uz/api/departments.asp');

        $departments = json_decode($response->getBody())->departments;

        if ($request->sub_id != 0) {
            $cameras = Camera::orWhere('section_id', '=', $request->section_id)
                ->where('sub_id', '=', $request->sub_id)
                ->paginate(8);
        } else {
            $cameras = $cameraRepository->getAll();
        }

        return view('dashboard.cameras.filter   ', [
            'sub_nulls' => $departments,
            'cameras' => $cameras,
            'api_url' => $this->api_url,
            'api_port' => $this->api_port
        ]);
    }

    public function indexFilter(Request $request)
    {
        $cameras = Camera::orWhere('section_id', '=', $request->section_id)
            ->where('sub_id', '=', $request->sub_id)
            ->paginate(8);
        return view('dashboard.cameras.index', ['cameras' => $cameras, 'api_url' => $this->api_url, 'api_port' => $this->api_port]);
    }

    public function ajaxGetRahbarId(Request $request)
    {
        $client = new \GuzzleHttp\Client();
        $response_sub_id = $client->request('POST', 'https://uniwork.buxdu.uz/api/departments.asp');
        $departments = json_decode($response_sub_id->getBody())->departments;
        $arr_sub_not_null = [];

        for ($i = 0; $i < count($departments); $i++) {
            if ($departments[$i]->id == $request->id) {
                $arr_sub_not_null[$i] = $departments[$i];
            }
        }

        return response([
            'departments' => $arr_sub_not_null
        ], 201);
    }

    public function ajaxGetSubId(Request $request)
    {
        $client = new \GuzzleHttp\Client();
        $response_sub_id = $client->request('POST', 'https://uniwork.buxdu.uz/api/departments_filter.asp?sub=' . $request->sub_id);
        $departments = json_decode($response_sub_id->getBody())->departments;

        return response([
            'departments' => $departments
        ], 201);
    }

    public function ajaxXonalar(Request $request)
    {
        $client = new \GuzzleHttp\Client();
        $response_rahbar_id = $client->request('POST', "https://uniwork.buxdu.uz/api/xonalar.asp?bino=" . $request->bino . "&" . "qavat=" . $request->qavat);

        $binolar = json_decode($response_rahbar_id->getBody())->xonalar;

        return response([
            'binolar' => $binolar
        ], 201);
    }

    /**
     * @return Factory|Application|View
     * @throws GuzzleException
     */
    public function create()
    {
        $client = new \GuzzleHttp\Client();
        $response = $client->request('GET', 'https://uniwork.buxdu.uz/api/departments.asp');
        $response_bino = $client->request('GET', 'https://uniwork.buxdu.uz/api/binolar.asp');

        $binolar = json_decode($response_bino->getBody())->binolar;
        $departments = json_decode($response->getBody())->departments;

        return view('dashboard.cameras.create', [
            'sub_nulls' => $departments,
            'binolar' => $binolar,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return RedirectResponse
     * @throws GuzzleException
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'link' => 'required',
            'sub_id' => 'required',
        ]);

        $client = new \GuzzleHttp\Client();
        $camera = new Camera();
        $name = $request->name;
        $link = $request->link;
        $favorite = $request->favorite ? $request->favorite : 0;
        $bolim_name = $request->bolim_name ? $request->bolim_name : 0;
        $sub_bolim_name = $request->sub_bolim_name ? $request->sub_bolim_name : 0;
        $section_id = $request->section_id ? $request->section_id : 0;
        $sub_id = $request->sub_id;
        $rahbar_id = $request->rahbar_id ? $request->rahbar_id : 0;
        $bino = $request->bino ? $request->bino : 0;
        $qavat = $request->qavat ? $request->qavat : 0;
        $xonalar = $request->xonalar ? $request->xonalar : 0;
        $xona_id = $request->xona_id ? $request->xona_id : 0;
        $uuid = Str::uuid()->toString();

        $data = json_decode("{
              \"name\": \"$name\",
              \"channels\": {
                  \"0\": {
                      \"name\": \"ch1\",
                      \"url\": \"$link\",
                      \"on_demand\": true,
                      \"debug\": false,
                      \"status\": 0
                  }
              }
          }");

        $client->request("POST", "http://$this->api_url:$this->api_port/stream/$uuid/add", [
            'headers' => [
                'Accept' => 'application/json',
                'Content-Type' => 'application/json',
            ],
            'auth' => [
                $this->api_login,
                $this->api_password
            ],
            'json' => $data
        ]);
        $camera->name = $name;
        $camera->link = $link;
        $camera->uuid = $uuid;
        $camera->section_id = $section_id;
        $camera->sub_id = $sub_id;
        $camera->rahbar_id = $rahbar_id;
        $camera->bino = $bino;
        $camera->qavat = $qavat;
        $camera->xonalar = $xonalar;
        $camera->favorite = $favorite;
        $camera->rahbarlar = implode(',', $request->rahbarlar);
        $camera->bolim_name = $bolim_name;
        $camera->sub_bolim_name = $sub_bolim_name;
        $camera->xona_id = $xona_id;
        $camera->save();
        return redirect()->route('cameras.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Camera $camera
     * @return Factory|View
     * @throws GuzzleException
     */
    public function edit(Camera $camera)
    {
        $client = new \GuzzleHttp\Client();
        $response = $client->request('GET', 'https://uniwork.buxdu.uz/api/departments.asp');
        $response_sub_id = $client->request('POST', 'https://uniwork.buxdu.uz/api/departments_filter.asp?sub=' . $camera->sub_id);
        $response_bino = $client->request('GET', 'https://uniwork.buxdu.uz/api/binolar.asp');
        $departments = json_decode($response->getBody())->departments;
        $sub_not_nulls = json_decode($response_sub_id->getBody())->departments;
        $response_binolar = $client->request('POST', 'https://uniwork.buxdu.uz/api/xonalar.asp?bino=' . $camera->bino . '&' . 'qavat=' . $camera->qavat);
        $xonalar = json_decode($response_binolar->getBody())->xonalar;


        $binolar = json_decode($response_bino->getBody())->binolar;

        return view('dashboard.cameras.edit', compact('camera', 'departments', 'sub_not_nulls', 'xonalar','binolar'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param Camera $camera
     * @return RedirectResponse
     * @throws GuzzleException
     */
    public function update(Request $request, Camera $camera)
    {
        $request->validate([
            'name' => 'required',
            'link' => 'required',
            'sub_id' => 'required',
        ]);

        $client = new \GuzzleHttp\Client();
        $cameras = Camera::find($camera->id);
        $name = $request->name;
        $link = $request->link;
        $favorite = $request->favorite ? $request->favorite : 0;
        $bolim_name = $request->bolim_name ? $request->bolim_name : 0;
        $sub_bolim_name = $request->sub_bolim_name ? $request->sub_bolim_name : 0;
        $section_id = $request->section_id ? $request->section_id : 0;
        $sub_id = $request->sub_id ? $request->sub_id : 0;
        $rahbar_id = $request->rahbar_id ? $request->rahbar_id : 0;
        $bino = $request->bino ? $request->bino : 0;
        $qavat = $request->qavat ? $request->qavat : 0;
        $xonalar = $request->xonalar ? $request->xonalar : 0;
        $xona_id = $request->xona_id ? $request->xona_id : 0;
        $data = json_decode("{
              \"name\": \"$name\",
              \"channels\": {
                  \"0\": {
                      \"name\": \"ch1\",
                      \"url\": \"$link\",
                      \"on_demand\": true,
                      \"debug\": false,
                      \"status\": 0
                  }
              }
          }");

resources/views/dashboard/cameras/filter.blade.php
@extends('dashboard.layout.master')
@section('content')
    <div class="row pt-4">
        <div class="col-md-12">
            <!-- general form elements -->
            <div class="card card-success">
                <div class="card-header">
                    <h3 class="card-title">Kameralar</h3>
                </div>
                <!-- /.card-header -->
                <!-- form start -->
                <form method="get" action="{{ route('cameras.index') }}" enctype="multipart/form-data">
{{--                    @csrf--}}
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label for="parent">Bo'lim</label>
                                    <select name="sub_id" id="parent" class="form-control section select2bs4" style="width: 100%; height: 100%">
                                        <option hidden value="0">Bo'limni tanlang!</option>
                                        @foreach($sub_nulls as $section)
                                            <option data-bolim-name="{{ $section->name }}" data-bolim-rahbar-id="{{ $section->rahbar_id }}" value="{{ $section->id }}">{{ $section->name }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group sec">
                                    <label for="section_id">Sub bo'limlar</label>
                                    <select name="section_id" id="section_id" class="form-control section_sub">
                                        <option hidden selected value="0">Sub bo'limni tanlang!</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer">
                        <button type="submit" class="btn btn-success">Izlash</button>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
    <div class="row pt-2">
        @foreach($cameras as $camera)
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3>
                            <a href="{{ route('cameras.edit',$camera) }}">{{ $camera->name }}</a>
                        </h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-2">

                        <video id="hls-example" class="video-js vjs-default-skin" width="380" height="300" controls autoplay>
                            <source  type="application/x-mpegURL" src="http://{{ $api_url }}:{{ $api_port }}/stream/{{ $camera->uuid }}/channel/0/hls/live/index.m3u8">
                        </video>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-2">
                        <form class="d-inline-block" action="{{ route('cameras.destroy', $camera) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger show_confirm" data-toggle="tooltip" type="submit">O'chirish</button>
                        </form>
                        <a class="btn btn-primary d-inline-block" href="{{ route('cameras.edit',$camera) }}">Tahrirlash</a>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
    <div class="d-flex align-items-center justify-content-center" style="margin-top: 20px;">
        {{ $cameras->links() }}
    </div>
@endsection
@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.14.1/videojs-contrib-hls.js"></script>
    <script src="https://vjs.zencdn.net/7.2.3/video.js"></script>
    <script type="text/javascript">
        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Siz haqiqatdan ushbu kamerani o'chirmoqchimisiz?`,
                // text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });
    </script>
    <script>
        let camera = document.querySelectorAll('#hls-example');
        camera.forEach(camera=>{
            var player = videojs(camera);
            player.play()
        });
    </script>
    <script>
        $(document).ready(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $(".section").change(function (){
                $('.bolim-name').remove();
                $('.sub_bolim_name').remove();
                $(".bolim").remove();
                $('.section_sub').html('');
                let sub_id = $(this).val();
                let options = $('.section option');
                for(let i=0; i<options.length; i++)
                {
                    if(sub_id === options[i].getAttribute('value')){
                        rahbar_bolim_id = options[i].getAttribute('data-bolim-rahbar-id');
                        bolim_name = options[i].getAttribute('data-bolim-name');
                    }
                }
                $.ajax({
                    url: '{{ route('ajax.getSubId') }}',
                    method: 'POST',
                    data: {
                        sub_id: sub_id,
                    },
                    success: function (response) {
                        var formoption = "";
                        $.each(response.departments, function(index, department) {
                            formoption += "<option data-sub-bolim-name='"+department.name+"' data-sub-rahbar-id='"+department.rahbar_id+"' data-section='"+ department.sub_id+"' value='"+department.id+"'>"+ (department.name) +"</option>";
                        });
                        formoption += "<option selected value='0'>Bo'limni tanlang</option>";
                        $("#add_input").append(`
                            <input name="rahbarlar[]" class="d-none bolim" value="${rahbar_bolim_id}"/>
                            <input name="bolim_name" class="d-none bolim-name" value="${bolim_name}"/>
                        `);

                        $(".section_sub").append(formoption);
                    },
                    // error: function (e) {
                    //     console.log(e);
                    // }
                });
            });

            $(".section_sub").change(function (){
                $('.sub_bolim_name').remove();
                $(".sub__bolim").remove();
                $('.rahbar_id').html('');
                let id = $(this).val();
                let sub_id = $(this).attr('data-section');
                let options = $('.section_sub option');
                for(let i=0; i<options.length; i++)
                {
                    if(id === options[i].getAttribute('value')){
                        rahbar_sub_id = options[i].getAttribute('data-sub-rahbar-id');
                        sub_bolim_name = options[i].getAttribute('data-sub-bolim-name');
                    }
                }
                $.ajax({
                    url: '{{ route('ajax.getRahbarId') }}',
                    method: 'POST',
                    data: {
                        id: id,
                        sub_id: sub_id,
                    },
                    success: function (response) {
                        var formoption = "";
                        $.each(response.departments, function(index, department) {
                            formoption += "<option data-section-rahbar='"+ department.sub_id+"' value='"+department.rahbar_id+"'>"+ department.rahbar +"</option>";
                        });
                        $("#add_input").append(`
                            <input name="rahbarlar[]" class="d-none sub__bolim" value="${rahbar_sub_id}"/>
                            <input name="sub_bolim_name" class="d-none sub_bolim_name" value="${sub_bolim_name}"/>
                        `);
                        $(".rahbar_id").append(formoption);
                    },

                    // error: function (e) {
                    //     console.log(e);
                    // }
                });
            });

            $('select[name="sub_id"]').change(function() {
                var parent = $(this).val();

                $("select[name='section_id']").val("");
                $(".sec").removeClass('d-none');

                $('select[name="section_id"] option').each(function() {
                    if ($(this).attr('data-section') == parent) {
                        $(this).show();
                    } else {
                        $(this).hide();
                    }

                });
            });

            $('select[name="section_id"]').change(function() {
                var parent = $(this).val();

                $("select[name='rahbar_id']").val("");
                $(".rahbar").removeClass('d-none');

                $('select[name="rahbar_id"] option').each(function() {
                    if ($(this).attr('data-section-rahbar') == parent) {
                        $(this).show();
                    } else {
                        $(this).hide();
                    }

                });
            });
        });
    </script>
@endpush

resources/views/dashboard/cameras/index.blade.php
@extends('dashboard.layout.master')
@section('content')
    <div class="row pt-2">
        @foreach($cameras as $camera)
            <div class="col-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3>
                            <a href="{{ route('cameras.edit',$camera) }}">{{ $camera->name }}</a>
                        </h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body p-2">

                        <video id="hls-example" class="video-js vjs-default-skin" width="380" height="300" controls autoplay>
                            <source  type="application/x-mpegURL" src="http://{{ $api_url }}:{{ $api_port }}/stream/{{ $camera->uuid }}/channel/0/hls/live/index.m3u8">
                        </video>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer p-2">
                        <form class="d-inline-block" action="{{ route('cameras.destroy', $camera) }}" method="post">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger show_confirm" data-toggle="tooltip" type="submit">O'chirish</button>
                        </form>
                        <a class="btn btn-primary d-inline-block" href="{{ route('cameras.edit',$camera) }}">Tahrirlash</a>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
{{--        <div class="row">--}}
            <div class="d-flex align-items-center justify-content-center" style="margin-top: 20px;">
            {{ $cameras->links() }}
            </div>
{{--        </div>--}}
@endsection
@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/videojs-contrib-hls/5.14.1/videojs-contrib-hls.js"></script>
    <script src="https://vjs.zencdn.net/7.2.3/video.js"></script>
    <script type="text/javascript">

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Siz haqiqatdan ushbu kamerani o'chirmoqchimisiz?`,
                // text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>

    <script>
        let camera = document.querySelectorAll('#hls-example');
        camera.forEach(camera=>{
            var player = videojs(camera);
            player.play()
        });
    </script>
@endpush